// Initialize Firebase using config
firebase.initializeApp(config.firebase);
const db = firebase.firestore();

// Story functionality
let stories = [];
let isAdmin = false;
let adminPassword = config.admin.password;

// Variables to store uploaded files and generated thumbnail
let uploadedImageData = null;
let uploadedVideoData = null;
let autoGeneratedThumbnail = null;

// Dashboard functionality
function toggleDashboard() {
  const dashboard = document.getElementById('adminDashboard');
  if (dashboard.style.display === 'none' || dashboard.style.display === '') {
    dashboard.style.display = 'flex';
    document.body.style.overflow = 'hidden';
    updateDashboardStats();
    loadRecentStories();
  } else {
    dashboard.style.display = 'none';
    document.body.style.overflow = 'auto';
  }
}

function updateDashboardStats() {
  if (!isAdmin) return;
  
  // Update total stories count
  document.getElementById('totalStories').textContent = stories.length;
  
  // Calculate total views
  const totalViews = stories.reduce((sum, story) => sum + (story.views || 0), 0);
  document.getElementById('totalViews').textContent = totalViews;
}

function loadRecentStories() {
  if (!isAdmin) return;
  
  const storiesList = document.getElementById('recentStoriesList');
  storiesList.innerHTML = '';
  
  if (stories.length === 0) {
    storiesList.innerHTML = '<p style="color: #888; text-align: center; padding: 20px;">No stories available yet.</p>';
    return;
  }
  
  // Show all stories
  stories.forEach((story, index) => {
    const storyElement = createDashboardStoryElement(story, index);
    storiesList.appendChild(storyElement);
  });
}

function createDashboardStoryElement(story, index) {
  const storyDiv = document.createElement('div');
  storyDiv.className = 'story-item-dashboard';
  
  let storyImage = (story.imageUrl) || ((story.videoInfo && story.videoInfo.thumbnail) ? story.videoInfo.thumbnail : 'https://img.alfrsantv.com/img/f17546454730791.jpg');
  
  storyDiv.innerHTML = `
    <img src="${storyImage}" alt="${story.title}" class="story-thumbnail" onerror="this.src='https://img.alfrsantv.com/img/f17546454730791.jpg'">
    <div class="story-details">
      <div class="story-title">${story.title || 'Untitled Story'}</div>
      <div class="story-meta">
        <span><i class="fa-solid fa-calendar"></i> ${story.timestamp}</span>
        <span><i class="fa-solid fa-eye"></i> ${story.views || 0} views</span>
      </div>
      <div class="story-content-preview">${story.content ? story.content.substring(0, 100) + (story.content.length > 100 ? '...' : '') : 'No content'}</div>
      <div class="story-actions">
        <button class="story-action-btn" onclick="viewStory(stories[${index}], ${index})">
          <i class="fa-solid fa-eye"></i> View
        </button>
        <button class="story-action-btn delete" onclick="deleteStory('${story.id}')">
          <i class="fa-solid fa-trash"></i> Delete
        </button>
      </div>
    </div>
  `;
  
  return storyDiv;
}

// Video platform detection
function detectVideoPlatform(url) {
  if (!url) return null;
  const urlLower = url.toLowerCase();

  // YouTube (including Shorts)
  if (urlLower.includes('youtube.com/watch') || urlLower.includes('youtu.be/') || urlLower.includes('youtube.com/shorts/')) {
    const videoId = extractYouTubeId(url);
    const isShorts = urlLower.includes('/shorts/');
    return {
      platform: 'youtube',
      videoId: videoId,
      embedUrl: `https://www.youtube.com/embed/${videoId}`,
      thumbnail: `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`,
      isShorts: isShorts,
      aspectRatio: isShorts ? 'portrait' : 'landscape'
    };
  }

  // Direct video file
  if (urlLower.match(/\.(mp4|webm|ogg|mov|avi|mkv)$/)) {
    return {
      platform: 'direct',
      videoUrl: url,
      aspectRatio: 'auto'
    };
  }

  return null;
}

function extractYouTubeId(url) {
  if (url.includes('/shorts/')) {
    const shortsMatch = url.match(/\/shorts\/([^/?&#]+)/);
    return shortsMatch ? shortsMatch[1] : null;
  }
  const regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|&v=)([^#&?]*).*/;
  const match = url.match(regExp);
  return (match && match[2].length === 11) ? match[2] : null;
}

// Admin functions
function handleGearClick() {
  if (isAdmin) {
    // If already admin, toggle dashboard visibility
    toggleDashboard();
  } else {
    showAdminLoginForGear();
  }
}

function showAdminLoginForGear() {
  const loginModal = document.createElement('div');
  loginModal.className = 'story-modal active';
  loginModal.style.zIndex = '1003';

  loginModal.innerHTML = `
    <div class="story-modal-content admin-modal">
      <button class="story-modal-close" onclick="closeAdminLoginModal()">
        <i class="fa-solid fa-times"></i>
      </button>
      <div class="story-modal-content-form">
        <div style="text-align: center; padding: 20px 0;">
          <div style="margin-bottom: 25px;">
            <i class="fa-solid fa-lock" style="font-size: 3rem; color: var(--accent-color); margin-bottom: 20px;"></i>
            <h3 style="color: var(--accent-color); margin-bottom: 15px; font-size: 1.8rem;">Admin Access Required</h3>
            <p style="color: #f5f5f5; font-size: 1.1rem; opacity: 0.9;">Enter admin password to access admin features</p>
          </div>
          <div style="margin-bottom: 25px;">
            <input type="password" id="adminPasswordInput" placeholder="Enter password..." style="width: 100%; padding: 15px; border: 2px solid var(--accent-color); border-radius: 12px; background: rgba(255, 255, 255, 0.1); color: white; font-size: 1.1rem; transition: all 0.3s ease;" onfocus="this.style.boxShadow='0 0 15px var(--border-glow)';" onblur="this.style.boxShadow='none';">
          </div>
          <div style="display: flex; gap: 15px; justify-content: center; margin-top: 10px;">
            <button onclick="closeAdminLoginModal()" style="background: linear-gradient(45deg, #555, #777); color: white; border: none; padding: 12px 25px; border-radius: 20px; cursor: pointer; font-size: 1rem; font-weight: 600; display: flex; align-items: center; gap: 8px; transition: all 0.3s ease; box-shadow: 0 4px 15px rgba(0,0,0,0.2);">
              <i class="fa-solid fa-times"></i> Cancel
            </button>
            <button onclick="verifyAdminPasswordForGear()" style="background: linear-gradient(45deg, var(--accent-color), var(--accent-color-secondary)); color: white; border: none; padding: 12px 25px; border-radius: 20px; cursor: pointer; font-size: 1rem; font-weight: 600; display: flex; align-items: center; gap: 8px; transition: all 0.3s ease; box-shadow: 0 4px 15px var(--border-glow);">
              <i class="fa-solid fa-check"></i> Login
            </button>
          </div>
        </div>
      </div>
    </div>
  `;

  document.body.appendChild(loginModal);
  document.body.style.overflow = 'hidden';

  setTimeout(() => {
    document.getElementById('adminPasswordInput').focus();
  }, 100);

  document.getElementById('adminPasswordInput').addEventListener('keypress', function (e) {
    if (e.key === 'Enter') {
      verifyAdminPasswordForGear();
    }
  });
}

// Add this new function to properly close the admin login modal
function closeAdminLoginModal() {
  const modal = document.querySelector('.story-modal.active');
  if (modal) {
    modal.remove();
  }
  document.body.style.overflow = 'auto';
}

function verifyAdminPasswordForGear() {
  const inputPassword = document.getElementById('adminPasswordInput').value;

  if (inputPassword === adminPassword) {
    isAdmin = true;
    sessionStorage.setItem('lemoAdminSession', 'true');
    document.querySelector('.story-modal.active').remove();
    document.body.style.overflow = 'auto';
    showNotification('Admin access granted! Welcome back! 🔓');

    updateGearIcon();
    renderStories();
  } else {
    showNotification('Incorrect password! Please try again! ❌');
    document.getElementById('adminPasswordInput').value = '';
    document.getElementById('adminPasswordInput').focus();
  }
}

function updateGearIcon() {
  const gearIcon = document.querySelector('.admin-gear');
  if (isAdmin) {
    gearIcon.classList.add('admin-active');
    gearIcon.innerHTML = '<i class="fa-solid fa-chart-line"></i>';
    gearIcon.title = 'Admin Dashboard - Click to open';
  } else {
    gearIcon.classList.remove('admin-active');
    gearIcon.innerHTML = '<i class="fa-solid fa-gear"></i>';
    gearIcon.title = 'Admin Settings';
  }
}

function showLogoutConfirm() {
  const logoutModal = document.createElement('div');
  logoutModal.className = 'story-modal active';
  logoutModal.style.zIndex = '1003';

  logoutModal.innerHTML = `
    <div class="story-modal-content admin-modal">
      <button class="story-modal-close" onclick="closeAdminLoginModal()">
        <i class="fa-solid fa-times"></i>
      </button>
      <div class="story-modal-content-form">
        <div style="text-align: center; padding: 20px 0;">
          <div style="margin-bottom: 25px;">
            <i class="fa-solid fa-sign-out-alt" style="font-size: 3rem; color: #ff6b6b; margin-bottom: 20px;"></i>
            <h3 style="color: var(--accent-color); margin-bottom: 15px; font-size: 1.8rem;">Logout Admin</h3>
          <p style="color: #f5f5f5; font-size: 1.1rem; opacity: 0.9;">Are you sure you want to logout from admin mode?</p>
        </div>
        <div style="display: flex; gap: 15px; justify-content: center; margin-top: 10px;">
          <button onclick="closeAdminLoginModal()" style="background: linear-gradient(45deg, var(--accent-color), var(--accent-color-secondary)); color: white; border: none; padding: 12px 25px; border-radius: 20px; cursor: pointer; font-size: 1rem; font-weight: 600; display: flex; align-items: center; gap: 8px; transition: all 0.3s ease; box-shadow: 0 4px 15px var(--border-glow);">
            <i class="fa-solid fa-times"></i> Cancel
          </button>
          <button onclick="logoutAdmin()" style="background: linear-gradient(45deg, #ff6b6b, #ee5a52); color: white; border: none; padding: 12px 25px; border-radius: 20px; cursor: pointer; font-size: 1rem; font-weight: 600; display: flex; align-items: center; gap: 8px; transition: all 0.3s ease; box-shadow: 0 4px 15px rgba(255, 107, 107, 0.4);">
            <i class="fa-solid fa-sign-out-alt"></i> Logout
          </button>
        </div>
      </div>
    </div>
  `;

  document.body.appendChild(logoutModal);
  document.body.style.overflow = 'hidden';
}

function logoutAdmin() {
  isAdmin = false;
  sessionStorage.removeItem('lemoAdminSession');
  document.querySelector('.story-modal.active').remove();
  document.body.style.overflow = 'auto';
  updateGearIcon();
  renderStories();
  
  // Close dashboard if it's open
  const dashboard = document.getElementById('adminDashboard');
  if (dashboard && (dashboard.style.display === 'flex' || dashboard.style.display === 'block')) {
    dashboard.style.display = 'none';
    document.body.style.overflow = 'auto';
  }
  
  showNotification('Admin logged out successfully! 👋');
}

// Story modal functions
function openStoryModalFromDashboard() {
  // Close the dashboard first
  toggleDashboard();
  // Then open the story modal
  openStoryModal();
}

function openStoryModal() {
  if (!isAdmin) {
    showAdminLoginForGear();
    return;
  }
  document.getElementById('storyModal').classList.add('active');
  document.body.style.overflow = 'hidden';
}

function closeStoryModal() {
  document.getElementById('storyModal').classList.remove('active');
  document.body.style.overflow = 'auto';
  document.getElementById('storyForm').reset();
  uploadedImageData = null;
  uploadedVideoData = null;
  document.getElementById('imageFileName').textContent = '';
  document.getElementById('videoFileName').textContent = '';
}

// Add story
async function addStory(title, content, imageUrl = null, videoUrl = null) {
  let videoInfo = detectVideoPlatform(videoUrl);

  const finalImage = imageUrl || (videoInfo && videoInfo.thumbnail) || null;

  const story = {
    title: title,
    content: content,
    imageUrl: finalImage,
    videoUrl: videoUrl,
    videoInfo: videoInfo,
    timestamp: new Date().toLocaleDateString(),
    views: 0,
    createdAt: firebase.firestore.FieldValue.serverTimestamp()
  };

  try {
    const docRef = await db.collection('stories').add(story);
    story.id = docRef.id;
    stories.unshift(story);
    renderStories();
    closeStoryModal();
    showNotification('Story added successfully! ✨');
  } catch (error) {
    console.error('Error adding story:', error);
    showNotification('Error adding story. Please try again! ❌');
  }
}

// Render stories
function renderStories() {
  const container = document.getElementById('storiesContainer');
  container.innerHTML = '';

  if (isAdmin) {
    const addButton = document.createElement('div');
    addButton.className = 'story-item add-story';
    addButton.onclick = openStoryModal;
    addButton.innerHTML = `
      <div class="add-button">
        <i class="fa-solid fa-plus"></i>
      </div>
      <div class="add-text">Create story</div>
    `;
    container.appendChild(addButton);
  }

  if (stories && stories.length > 0) {
    stories.forEach((story, index) => {
      const storyElement = createStoryElement(story, index);
      container.appendChild(storyElement);
    });
  } else if (!isAdmin) {
    const noStoriesMessage = document.createElement('div');
    noStoriesMessage.style.cssText = `
      text-align: center;
      padding: 20px;
      color: #888;
      font-style: italic;
    `;
    noStoriesMessage.textContent = 'No stories available yet.';
    container.appendChild(noStoriesMessage);
  }
  
  // Update dashboard stats if admin and dashboard is open
  if (isAdmin) {
    updateDashboardStats();
    loadRecentStories();
  }
}

function createStoryElement(story, index) {
  const storyDiv = document.createElement('div');
  storyDiv.className = 'story-item';
  storyDiv.onclick = () => viewStory(story, index);

  let storyImage = (story.imageUrl) || ((story.videoInfo && story.videoInfo.thumbnail) ? story.videoInfo.thumbnail : 'https://img.alfrsantv.com/img/f17546454730791.jpg');

  storyDiv.innerHTML = `
    <img src="${storyImage}" alt="${story.title}" class="story-image" onerror="this.src='https://img.alfrsantv.com/img/f17546454730791.jpg'">
    <div class="story-profile">
      <img src="https://img.alfrsantv.com/img/f17546454730791.jpg" alt="Profile">
    </div>
    <div class="story-overlay">
      <i class="fa-solid fa-play"></i>
    </div>
  `;

  return storyDiv;
}

async function viewStory(story, index) {
  story.views++;
  try {
    await db.collection('stories').doc(story.id).update({
      views: story.views
    });
  } catch (error) {
    console.error('Error updating view count:', error);
    story.views--;
  }

  const viewerModal = document.createElement('div');
  viewerModal.className = 'story-modal active';
  viewerModal.style.zIndex = '1001';

  viewerModal.innerHTML = `
    <div class="story-modal-content story-viewer">
      <button class="story-modal-close" onclick="this.parentElement.parentElement.remove(); document.body.style.overflow = 'auto';">
        <i class="fa-solid fa-times"></i>
      </button>
      <div class="story-content-display">
        <h3 class="story-title-display">${story.title || 'Untitled Story'}</h3>

        ${story.videoUrl ? `
          <div class="story-media-container">
            ${story.videoInfo && story.videoInfo.platform === 'youtube' ? `
              <div style="position: relative; width: 100%; padding-bottom: ${story.videoInfo.aspectRatio === 'portrait' ? '177.78%' : '56.25%'};">
                <iframe
                  src="${story.videoInfo.embedUrl}?autoplay=0&rel=0"
                  style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border: none;"
                  allowfullscreen>
                </iframe>
              </div>
            ` : `
              <div>
                <video controls style="width: 100%; height: auto; max-height: 70vh; background: #000; object-fit: contain;">
                  <source src="${story.videoUrl}" type="video/mp4">
                  Your browser does not support the video tag.
                </video>
              </div>
            `}
          </div>
        ` : ''}

        ${story.imageUrl && !story.videoUrl ? `
          <div class="story-media-container" style="display: flex; justify-content: center;">
            <img src="${story.imageUrl}" alt="${story.title}" style="max-width: 100%; max-height: 60vh;">
          </div>
        ` : ''}

        ${story.content ? `
          <div class="story-content-text">
            ${story.content.replace(/\n/g, '<br>')}
          </div>
        ` : ''}

        <div class="story-meta-info">
          <span><i class="fa-solid fa-calendar"></i> ${story.timestamp}</span>
          <span><i class="fa-solid fa-eye"></i> ${story.views} views</span>
        </div>

        <div class="modal-action-buttons">
          ${isAdmin ? `<button onclick="deleteStory('${story.id}')" class="modal-action-button delete">
            <i class="fa-solid fa-trash"></i> Delete
          </button>` : ''}
          <button onclick="this.parentElement.parentElement.parentElement.parentElement.remove(); document.body.style.overflow = 'auto';" class="modal-action-button close">
            <i class="fa-solid fa-check"></i> Close
          </button>
        </div>
      </div>
    </div>
  `;

  document.body.appendChild(viewerModal);
  document.body.style.overflow = 'hidden';
}

async function deleteStory(storyId) {
  if (confirm('Are you sure you want to delete this story?')) {
    try {
      await db.collection('stories').doc(storyId).delete();
      stories = stories.filter(story => story.id !== storyId);
      renderStories();
      document.querySelector('.story-modal.active').remove();
      document.body.style.overflow = 'auto';
      showNotification('Story deleted successfully! 🗑️');
    } catch (error) {
      console.error('Error deleting story:', error);
      showNotification('Error deleting story. Please try again! ❌');
    }
  }
}

// Load stories from Firebase
async function loadStories() {
  try {
    const snapshot = await db.collection('stories')
      .orderBy('createdAt', 'desc')
      .limit(20)
      .get();

    stories = [];
    snapshot.forEach(doc => {
      const story = doc.data();
      story.id = doc.id;
      stories.push(story);
    });

    renderStories();
  } catch (error) {
    console.error('Error loading stories:', error);
    showNotification('Error loading stories. Please refresh the page! ❌');
  }
}

function showNotification(message) {
  const notification = document.createElement('div');
  notification.style.cssText = `
    position: fixed;
    top: 20px;
    right: 20px;
    background: linear-gradient(45deg, var(--accent-color), var(--accent-color-secondary));
    color: white;
    padding: 15px 25px;
    border-radius: 25px;
    z-index: 10000;
    font-weight: 600;
    box-shadow: 0 5px 20px var(--border-glow);
    animation: slideIn 0.3s ease;
  `;
  notification.textContent = message;

  document.body.appendChild(notification);

  setTimeout(() => {
    notification.style.animation = 'slideOut 0.3s ease';
    setTimeout(() => notification.remove(), 300);
  }, 3000);
}

// File upload handling

// Add event listeners after DOM content loads
document.addEventListener('DOMContentLoaded', function () {
  // Add event listener for image file selection
  document.getElementById('storyImageFile').addEventListener('change', function (e) {
    const file = e.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = function (e) {
        uploadedImageData = e.target.result;
        document.getElementById('imageFileName').textContent = file.name;
      };
      reader.readAsDataURL(file);
    }
  });

  // Add event listener for video file selection
  document.getElementById('storyVideoFile').addEventListener('change', function (e) {
    const file = e.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = function (e) {
        uploadedVideoData = e.target.result;
        document.getElementById('videoFileName').textContent = file.name;
        
        // Automatically generate thumbnail when video is uploaded
        generateAutoThumbnail(file);
      };
      reader.readAsDataURL(file);
    } else {
      // Hide thumbnail generation status when no video is selected
      document.getElementById('thumbnailGenerationStatus').style.display = 'none';
      autoGeneratedThumbnail = null;
    }
  });
  
  // Update form submission to use auto-generated thumbnail
  document.getElementById('storyForm').addEventListener('submit', function (e) {
    e.preventDefault();

    const title = document.getElementById('storyTitle').value.trim();
    const content = document.getElementById('storyContent').value.trim();
    const imageUrl = document.getElementById('storyImage').value.trim();
    const videoUrl = document.getElementById('storyVideo').value.trim();

    // Use auto-generated thumbnail if available, otherwise use other image sources
    const finalImageUrl = autoGeneratedThumbnail || uploadedImageData || imageUrl || null;
    const finalVideoUrl = uploadedVideoData || videoUrl || null;

    if (title || content || finalImageUrl || finalVideoUrl) {
      addStory(title || '', content || '', finalImageUrl, finalVideoUrl);
      uploadedImageData = null;
      uploadedVideoData = null;
      autoGeneratedThumbnail = null;
      document.getElementById('imageFileName').textContent = '';
      document.getElementById('videoFileName').textContent = '';
      // Reset thumbnail generation status
      document.getElementById('thumbnailGenerationStatus').style.display = 'none';
    } else {
      showNotification('Please fill in at least one field! 📝');
    }
  });

  // Close modal when clicking outside
  document.getElementById('storyModal').addEventListener('click', function (e) {
    if (e.target === this) {
      closeStoryModal();
    }
  });

  // Scroll stories function
  window.scrollStories = function (direction = 'right') {
    const container = document.getElementById('storiesContainer');
    const distance = Math.round(container.clientWidth * 0.8);
    container.scrollBy({
      left: direction === 'left' ? -distance : distance,
      behavior: 'smooth'
    });
    setTimeout(updateStoryNav, 350);
  };

  // Show/hide left/right nav buttons based on scroll position
  function updateStoryNav() {
    const container = document.getElementById('storiesContainer');
    const leftBtn = document.getElementById('storyNavLeft');
    const rightBtn = document.getElementById('storyNavRight');
    if (!container || !leftBtn || !rightBtn) return;
    leftBtn.style.display = container.scrollLeft > 4 ? 'flex' : 'none';
    rightBtn.style.display = 'flex';
  }

  // Initialize
  loadStories();

  const sc = document.getElementById('storiesContainer');
  if (sc) {
    sc.addEventListener('scroll', updateStoryNav, { passive: true });
    window.addEventListener('resize', updateStoryNav);
    updateStoryNav();
  }

  // Check if admin session exists
  const adminSession = sessionStorage.getItem('lemoAdminSession');
  if (adminSession === 'true') {
    isAdmin = true;
    updateGearIcon();
    renderStories();
  }
});

// Automatic thumbnail generation function
async function generateAutoThumbnail(videoFile) {
  if (!videoFile) return;
  
  // Show thumbnail generation status
  const thumbnailStatus = document.getElementById('thumbnailGenerationStatus');
  const thumbnailStatusText = document.getElementById('thumbnailStatusText');
  thumbnailStatus.style.display = 'block';
  thumbnailStatusText.innerHTML = '<i class="fa-solid fa-spinner fa-spin"></i> Generating thumbnail from video...';
  
  try {
    // Create video element
    const video = document.createElement('video');
    video.src = URL.createObjectURL(videoFile);
    
    // Wait for video to load metadata
    await new Promise((resolve, reject) => {
      video.onloadedmetadata = resolve;
      video.onerror = reject;
    });
    
    const duration = video.duration;
    
    // Try to get a frame from the middle of the video
    const timePoint = duration / 2;
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    
    // Set canvas dimensions (maintain aspect ratio but limit size)
    video.currentTime = timePoint;
    
    // Wait for frame to load
    await new Promise((resolve) => {
      video.ontimeupdate = () => {
        // Check if video has valid frame data (avoid black screens)
        if (video.videoWidth > 0 && video.videoHeight > 0) {
          // Limit canvas size to avoid large data URLs
          const maxWidth = 800;
          const maxHeight = 600;
          let width = video.videoWidth;
          let height = video.videoHeight;
          
          // Scale down if necessary
          if (width > maxWidth) {
            height = (height * maxWidth) / width;
            width = maxWidth;
          }
          if (height > maxHeight) {
            width = (width * maxHeight) / height;
            height = maxHeight;
          }
          
          canvas.width = width;
          canvas.height = height;
          ctx.drawImage(video, 0, 0, width, height);
          resolve();
        } else {
          // If we can't get a valid frame, try a slightly different time
          video.currentTime = timePoint + 0.1;
        }
      };
      // Fallback in case ontimeupdate doesn't fire
      setTimeout(resolve, 1000);
    });
    
    // Convert to data URL with quality optimization
    const dataUrl = canvas.toDataURL('image/jpeg', 0.8);
    autoGeneratedThumbnail = dataUrl;
    
    // Also set as story image
    uploadedImageData = dataUrl;
    
    // Update status to show success
    thumbnailStatusText.innerHTML = '<i class="fa-solid fa-check" style="color: #4CAF50;"></i> Thumbnail automatically generated and will be used for your story!';
    
    // Hide status after 3 seconds
    setTimeout(() => {
      thumbnailStatus.style.display = 'none';
    }, 3000);
    
  } catch (error) {
    console.error('Error generating thumbnail:', error);
    thumbnailStatusText.innerHTML = '<i class="fa-solid fa-exclamation-triangle" style="color: #F44336;"></i> Error generating thumbnail. Please try again.';
    
    // Hide status after 3 seconds
    setTimeout(() => {
      thumbnailStatus.style.display = 'none';
    }, 3000);
  }
}
